spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/miniature-payroll_db
    username: postgres
    password: ${postgresql}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

evs:
  jwt-security: ${jwt-security}

evs2:
  admin-password: ${admin-password}

evs3:
  account-password: ${account-password}